// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Image from "next/image";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} scrollbar-hide relative antialiased`}>
//         <Image
//           src="/bg.jpg"
//           alt="Romantic Background"
//           fill
//           className="object-cover bg-amber-800"
//           priority
//         />

//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anniversary Gift", // Title ကို ပြင်ပေးထားပါတယ်
  description: "A private romantic experience", // Description ကို ပြင်ပေးထားပါတယ်
  manifest: "/manifest.json", // 🌟 ဒီစာကြောင်းလေးကို အသစ် သွားထည့်ပေးပါ
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} scrollbar-hide antialiased`}>
        <SpeedInsights />
        <Analytics /> {/* Vercel Analytics ကို ထည့်သွင်းထားပါတယ် */}
        {/* Step 1: Background Image ကို အောက်ဆုံး Layer အဖြစ် (fixed, -z-50) ထားပါမည် */}
        <div className="fixed inset-0 -z-50">
          <Image
            src="/bg.jpg"
            alt="Romantic Background"
            fill
            className="object-cover" // bg-amber-800 ကို ဖြုတ်လိုက်ပါပြီ (Image ရှိနေလို့ မလိုပါ)
            priority
          />
        </div>
        {/* Step 2: Content များကို အပေါ်ဆုံး Layer (z-0) တွင် ထားပါမည် */}
        <div className="relative z-0 min-h-screen">{children}</div>
      </body>
    </html>
  );
}